// AUTO-GENERATED by scripts/build-toolkit-schema-data.js — do not hand-edit.
// Source: the toolkit panel's .tkc card markup (already rendered verbatim
// in data/resourcePanels.ts). This file is a STRUCTURAL EXTRACT of the same
// cards (name, tagline, description, url, category) used ONLY to generate
// ItemList JSON-LD schema on /toolkit — it does not replace or alter the
// verbatim HTML rendering of the toolkit page itself.

export interface ToolkitEntry {
  name: string;
  tagline: string;
  description: string;
  url: string;
  category: string;
}

export const toolkitEntries: ToolkitEntry[] = [
  {
    "name": "ToolSuite",
    "tagline": "Ecom Research Suite · Bundle",
    "description": "All-in-one ecommerce research suite for dropshippers. Combines product research, competitor analysis, and store tracking in a single dashboard. Designed for operators who want consolidated data without switching between multiple tools.",
    "url": "https://whop.com/toolsuite?a=internetjames",
    "category": "All-In-One Tool Access"
  },
  {
    "name": "LuxuryTools",
    "tagline": "Bundle · 20+ Tools · $29/mo",
    "description": "All-in-one access pass: GetHookd, AdSpy, WinningHunter, PiPiAds, ShopHunter, CreativeOS, SimilarWeb, Kalodata, Brandsearch, Minea, and more — bundled for $29/month. The smartest way to stack tools without paying for each separately.",
    "url": "https://whop.com/luxury-paid?a=internetjames",
    "category": "All-In-One Tool Access"
  },
  {
    "name": "Kalodata",
    "tagline": "TikTok Shop Intelligence",
    "description": "TikTok Shop sales data, trending products, top creator performance, and revenue estimates. Find products generating $50K–$500K/month on TikTok before testing on Meta. Shows revenue trajectory, pricing, and which creator angles are winning.",
    "url": "https://kalodata.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "Minea",
    "tagline": "Meta · TikTok · Pinterest Ad Spy",
    "description": "The most comprehensive ad spy tool. Shows Meta, TikTok, and Pinterest ads with engagement data, estimated spend, and targeting info. Filter by active ads 30+ days to find what's actually converting. Best for proven cross-platform winners.",
    "url": "https://minea.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "PipiAds",
    "tagline": "TikTok Ad Spy",
    "description": "TikTok ad spy tool with winning product rankings, creative performance data, and store revenue estimates. Includes a product search engine that surfaces viral items before they peak. Good complement to Kalodata for TikTok research.",
    "url": "https://pipiads.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "AdSpy",
    "tagline": "Facebook Ad Database",
    "description": "Massive Facebook ad database with powerful search filters. Best for deep research on specific competitors or niches. Search by likes, shares, comments, ad text, or landing page URL. Comprehensive dataset for serious operators.",
    "url": "https://adspy.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "BigSpy",
    "tagline": "Multi-Platform Ad Spy",
    "description": "Ad spy tool covering Facebook, Instagram, TikTok, Twitter, Pinterest, and YouTube. Over 1 billion ads in the database. Free tier available. Good for researching across platforms when you want broad coverage without paying for multiple tools.",
    "url": "https://bigspy.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "Winning Hunter",
    "tagline": "Product & Ad Research",
    "description": "Discover winning dropshipping products and the ads behind them. Shows store revenue estimates, ad creative libraries, and trending products across Meta and TikTok. Useful for reverse-engineering what's already printing.",
    "url": "https://winninghunter.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "ShopHunter",
    "tagline": "Shopify Store Revenue Spy",
    "description": "Spy on competitor Shopify store revenue in real time. Track daily sales, product launches, and revenue trends across any store. Invaluable for finding stores that are currently scaling — then sourcing the products they're selling.",
    "url": "https://shophunter.io",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "AdCads AI",
    "tagline": "AI Ad Creative Platform",
    "description": "AI-powered platform for generating scroll-stopping ad creatives at scale. Input your product details and let AI produce static and video ad variants optimised for Meta and TikTok. Drastically cuts creative production time and cost.",
    "url": "https://adcads.ai",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "Brandsearch",
    "tagline": "Competitive Intelligence",
    "description": "Multi-purpose competitive intelligence tool for ecommerce. Benchmarks website traffic, reveals Shopify store revenue estimates, product counts, themes, tech stacks, and analyzes Meta & TikTok ads. Validates niches and seizes opportunities fast.",
    "url": "https://brandsearch.co?ref=acharya",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "SimilarWeb",
    "tagline": "Traffic & Market Intelligence",
    "description": "Analyze any website's traffic sources, audience demographics, and top pages. Use to assess competitor store traffic, discover where they're getting visitors from, and benchmark your own growth. Essential for market research and validation.",
    "url": "https://similarweb.com",
    "category": "Product Research & Winning Products"
  },
  {
    "name": "CJDropshipping",
    "tagline": "Primary Fulfillment Supplier · Free",
    "description": "Primary supplier for testing phase. Free to join. Ships globally with 7–12 day delivery to US/UK. Auto-fulfillment integration with Shopify. Handles warehousing, packaging, and shipping. Use until you hit 10–20 orders/day, then move to a sourcing agent.",
    "url": "https://cjdropshipping.com",
    "category": "Product Sourcing & Suppliers"
  },
  {
    "name": "Apify",
    "tagline": "Web Scraping & Automation",
    "description": "Web scraping and automation platform. Use pre-built scrapers to extract product data from Amazon, AliExpress, or competitor stores at scale. Advanced operators use it to monitor price changes, reviews, and stock levels automatically.",
    "url": "https://apify.com",
    "category": "Market Research & Data Collection"
  },
  {
    "name": "AfterLib",
    "tagline": "Ad Creative Library",
    "description": "Massive swipe file of high-performing ecommerce ads across Facebook and TikTok. Search by niche, format, or engagement. Use as a creative inspiration library — study what's working and adapt angles for your own products.",
    "url": "https://afterlib.com",
    "category": "Ad Angles & Creative Research"
  },
  {
    "name": "Creative OS",
    "tagline": "Ad Creative Templates",
    "description": "Massive library of proven ad templates for Facebook and TikTok. Static ads, video scripts, UGC formats — all designed by operators who've tested them. Use as a starting point instead of building from scratch. Cuts creative production time dramatically.",
    "url": "https://creativeos.io",
    "category": "Ad Angles & Creative Research"
  },
  {
    "name": "GetHookd AI",
    "tagline": "Ad Library · 68M+ Ads · AI Creative",
    "description": "Searchable ad library with 68M+ ads across Meta, TikTok, Google, and Pinterest. AI-powered creative intelligence surfaces what's converting. Includes 296 winning products doing $10K–$100K/day. Purpose-built for dropshippers: ad research, creative ideas, and winning product discovery in one place.",
    "url": "https://gethookd.ai",
    "category": "Ad Angles & Creative Research"
  },
  {
    "name": "Atria",
    "tagline": "Ad Creative Intelligence",
    "description": "AI-powered creative intelligence platform. Analyzes top-performing ads to surface patterns in hooks, formats, and angles that convert. Helps operators understand why specific creatives work — not just what's working — so they can produce more winners with every batch.",
    "url": "https://tryatria.com",
    "category": "Ad Angles & Creative Research"
  },
  {
    "name": "HeyGen",
    "tagline": "AI Avatar Video · Multi-Language",
    "description": "Professional-grade AI avatar video platform. Create talking-head ads with hyper-realistic AI presenters in 40+ languages. Clone your own voice and appearance. Used by major DTC brands for localized ad campaigns. Best for operators scaling into multiple international markets.",
    "url": "https://heygen.com",
    "category": "AI Content Creation"
  },
  {
    "name": "Creatify AI",
    "tagline": "AI Video Ad Generator · URL-to-Video",
    "description": "Input your product URL and Creatify generates full video ads with AI avatars, voiceover, captions, and music in minutes. Creates 15–30 second ads ready to launch on Meta and TikTok. Use to generate creative volume fast — especially when you need 30+ variations.",
    "url": "https://creatify.ai",
    "category": "AI Content Creation"
  },
  {
    "name": "MakeUGC",
    "tagline": "AI UGC Video Ads · 300+ Avatars",
    "description": "Create authentic-looking UGC-style video ads using AI avatars — without hiring real creators. 300+ avatars, 29 languages, custom scenes. AI avatars can physically \"hold\" your product. Saves up to 70% vs. traditional UGC production. Use code 2026DISCOUNT at checkout.",
    "url": "https://www.makeugc.ai/?ref=2026discount",
    "category": "AI Content Creation"
  },
  {
    "name": "ElevenLabs",
    "tagline": "AI Voiceover · Voice Cloning",
    "description": "Best-in-class AI voice generation. Create natural-sounding voiceovers in any accent or language from any script. Clone your own voice or choose from 3,000+ voices. Use for product demo narration, ad scripts, and customer testimonial-style voiceovers. Free tier available.",
    "url": "https://elevenlabs.io",
    "category": "AI Content Creation"
  },
  {
    "name": "OpusClip",
    "tagline": "AI Long-Form to Short-Form Clips",
    "description": "AI tool that cuts long videos into short, high-engagement clips optimized for TikTok, Reels, and YouTube Shorts. If you have any long-form product demos, reviews, or testimonials — OpusClip extracts the best 30–60 second moments automatically with captions.",
    "url": "https://opus.pro",
    "category": "AI Content Creation"
  },
  {
    "name": "InfiniteTalk AI",
    "tagline": "AI Lip-Sync Avatar Video",
    "description": "AI lip-sync and talking avatar tool. Animate any image or video with your audio — perfect lip-sync, head movement, and facial expressions. Create unlimited-length talking-head videos for product demos and UGC-style ads without filming anyone. Multi-speaker support for dialogue ads.",
    "url": "https://www.infinitetalk.net/?i=h3l9c",
    "category": "AI Content Creation"
  },
  {
    "name": "Replo",
    "tagline": "Shopify Page Builder",
    "description": "Drag-and-drop landing page builder natively integrated with Shopify. Build custom product pages, advertorials, and sales funnels without code. Integrates with Klaviyo, Attentive, and major analytics tools. Used by brands doing $1M+/year.",
    "url": "https://replo.app",
    "category": "Landing Pages & Store Building"
  },
  {
    "name": "GemPages",
    "tagline": "Shopify Page Builder",
    "description": "Visual page builder with 100+ ready-made templates optimised for conversion. Drag-and-drop editor for product pages, landing pages, and homepages. Good for non-technical operators who want to move beyond Shopify's default Dawn theme after validation.",
    "url": "https://apps.shopify.com/gem-pages",
    "category": "Landing Pages & Store Building"
  },
  {
    "name": "Zipify Pages",
    "tagline": "Shopify Landing Page Builder",
    "description": "High-converting landing page and advertorial builder for Shopify. Pre-built templates designed by operators running 7-figure stores. Build dedicated landing pages per angle once you've validated a winner. Purpose-built for paid traffic, not generic page builders.",
    "url": "https://apps.shopify.com/zipify-pages",
    "category": "Landing Pages & Store Building"
  },
  {
    "name": "Hotjar",
    "tagline": "Heatmaps & Session Recordings",
    "description": "Heatmaps, session recordings, and conversion funnels. See exactly where visitors drop off on your product page, what they click, and where they scroll to. Essential for diagnosing low conversion rates — free tier sufficient for most early-stage stores.",
    "url": "https://hotjar.com",
    "category": "Conversion Rate Optimization"
  },
  {
    "name": "Intelligems",
    "tagline": "Price A/B Testing",
    "description": "Split-test your pricing directly on Shopify. Show different prices to different visitors and measure the actual impact on revenue and conversion rate. Most operators guess at pricing — Intelligems lets you test your way to the optimal price point.",
    "url": "https://intelligems.io",
    "category": "Conversion Rate Optimization"
  },
  {
    "name": "Omnisend",
    "tagline": "Email + SMS + Push Automation",
    "description": "Email, SMS, and web push automation in one platform. Strong Shopify integration. Better pricing than Klaviyo at lower contact counts. AI-powered subject line generator and content tools included. Good alternative to Klaviyo if you're cost-sensitive at early stages.",
    "url": "https://omnisend.com",
    "category": "Email & Customer Retention"
  },
  {
    "name": "Klaviyo",
    "tagline": "Email + SMS · Industry Standard",
    "description": "Industry-standard ecommerce email + SMS platform. Deep Shopify integration, pre-built abandoned cart flows, and advanced segmentation. Free up to 250 contacts — enough to validate your email strategy before spending a dollar. At 1,000 contacts it's $45/month and still the best ROI of any retention tool in the stack.",
    "url": "https://klaviyo.com",
    "category": "Email & Customer Retention"
  },
  {
    "name": "Upsell",
    "tagline": "In-Cart & Checkout Upsells",
    "description": "Shopify upsell app for in-cart and checkout upsell offers. Show targeted product recommendations before and during checkout to increase average order value. Works alongside AfterSell for a full pre- and post-purchase upsell stack.",
    "url": "https://apps.shopify.com/upsell",
    "category": "Upsells & AOV"
  },
  {
    "name": "AfterSell",
    "tagline": "Post-Purchase Upsells",
    "description": "Post-purchase upsell funnels shown immediately after checkout. Customers are in a buying state — a well-placed upsell here converts at 15–30% with zero extra ad spend. The single highest-ROI add on any Shopify store once you have sales flow.",
    "url": "https://apps.shopify.com/aftersell",
    "category": "Upsells & AOV"
  },
  {
    "name": "Kaching Bundles",
    "tagline": "Bundle & Volume Discounts · AOV",
    "description": "Create buy-more-save-more bundles and volume discount offers directly on your product page. \"Buy 2 get 15% off, Buy 3 get 25% off\" is one of the highest-ROI AOV tactics in ecom — increases average order value without any extra ad spend. Works alongside AfterSell for a full AOV + post-purchase stack.",
    "url": "https://apps.shopify.com/kaching-bundle-quantity-breaks",
    "category": "Upsells & AOV"
  },
  {
    "name": "RedTrack",
    "tagline": "Performance Marketing Attribution",
    "description": "Performance marketing platform built for media buyers. Integrates with 200+ ad networks and tools. Strong for agencies and multi-brand operators running campaigns across Facebook, Google, and TikTok simultaneously. Sophisticated segmentation and click-level attribution.",
    "url": "https://redtrack.io",
    "category": "Tracking & Attribution"
  },
  {
    "name": "Wetracked.io",
    "tagline": "Server-Side Ad Tracking",
    "description": "Server-side tracking that captures 98–100% of conversions (vs. ~60% with Meta's browser pixel alone). Fixes iOS data loss, ad blockers, and cross-device gaps. Pushes accurate conversion data directly back into Meta's ad algorithm so it can optimize properly. No developer required.",
    "url": "https://wetracked.io",
    "category": "Tracking & Attribution"
  },
  {
    "name": "Triple Whale",
    "tagline": "Ecom Analytics Dashboard",
    "description": "All-in-one ecommerce analytics platform. Aggregates data from Shopify, Meta, Google, and TikTok into a single dashboard. Tracks profit, LTV, ROAS, and customer journeys in one view. Best for operators at $30K+/month who need unified reporting and multi-channel attribution.",
    "url": "https://triplewhale.com",
    "category": "Tracking & Attribution"
  },
  {
    "name": "Chargeflow",
    "tagline": "Automated Chargeback Recovery",
    "description": "Fully automated chargeback dispute management. Chargeflow fights chargebacks on your behalf using AI — you pay only when they win. Integrates with Shopify, Stripe, and PayPal. At scale, chargebacks can eat 1–3% of revenue; automated fighting recovers a significant portion without any manual effort.",
    "url": "https://chargeflow.io",
    "category": "Payments, Chargebacks & Disputes"
  },
  {
    "name": "ChargeBlast",
    "tagline": "Chargeback Alerts & Prevention",
    "description": "Chargeback alert system that notifies you of incoming disputes before they're filed — giving you time to issue a refund and avoid the chargeback entirely. Prevention is cheaper than fighting. Use alongside Chargeflow for a full-coverage chargeback strategy.",
    "url": "https://chargeblast.com",
    "category": "Payments, Chargebacks & Disputes"
  },
  {
    "name": "Disputifier",
    "tagline": "Chargeback Dispute Fighting",
    "description": "Automated chargeback dispute service with high win rates. Builds and submits compelling dispute responses using order data, tracking info, and communication logs. Alternative to Chargeflow — compare their win rates and pricing for your specific payment processor before choosing.",
    "url": "https://disputifier.com",
    "category": "Payments, Chargebacks & Disputes"
  },
  {
    "name": "Gorgias",
    "tagline": "Customer Support Helpdesk",
    "description": "Shopify-native customer support platform. Unifies email, chat, social DMs, and order management in one inbox. AI handles repetitive tickets automatically. Use when support volume becomes unmanageable — typically at 20–30 orders/day. Cuts support time by 50–70%.",
    "url": "https://gorgias.com",
    "category": "Customer Support"
  },
  {
    "name": "CommSlayer",
    "tagline": "Facebook Ad Comment Management",
    "description": "Manage and moderate your Facebook ad comments at scale. Auto-hide negative comments, respond to buyer questions, and prevent competitors from poisoning your comment sections. Essential once your ads get significant comment volume.",
    "url": "https://apps.shopify.com/commslayer",
    "category": "Customer Support"
  },
  {
    "name": "OnlineJobs.ph",
    "tagline": "Filipino VAs & Staff",
    "description": "The go-to platform for hiring Filipino virtual assistants. Operators use it to hire part-time or full-time VAs for customer service, order management, ad reporting, and store operations. $3–6/hour for reliable, English-speaking support.",
    "url": "https://onlinejobs.ph",
    "category": "Team & Hiring"
  },
  {
    "name": "Upwork",
    "tagline": "Freelancers · Sourcing Agents",
    "description": "Find China-based sourcing agents, video editors, store builders, and VA support. Search \"China sourcing agent\" to find agents who'll negotiate better COGS than CJ at volume. Review past jobs carefully. Most operators use Upwork to hire their first agent at 10–20 orders/day.",
    "url": "https://upwork.com",
    "category": "Team & Hiring"
  },
  {
    "name": "Fiverr",
    "tagline": "Freelancers · Creatives",
    "description": "Freelance marketplace for one-off tasks: ad editing, logo design, product photography, copywriting, and store builds. Better for creative tasks than Upwork. Use for quick-turnaround work when you don't need a long-term hire.",
    "url": "https://fiverr.com",
    "category": "Team & Hiring"
  },
  {
    "name": "Bizee",
    "tagline": "LLC Formation · $0 Base Price",
    "description": "Free LLC formation (you pay state fees only). Includes a free year of registered agent service. Faster turnaround than many competitors. Good alternative to ZenBusiness if you want the lowest upfront cost. Over 1M businesses formed.",
    "url": "https://bizee.com",
    "category": "Business Formation & Administration"
  },
  {
    "name": "ZenBusiness",
    "tagline": "LLC Formation · Registered Agent",
    "description": "Form your LLC quickly and affordably. ZenBusiness handles the paperwork, registered agent service, and compliance filing. Starting at $0 + state fees. Most dropshippers form an LLC before scaling to protect personal assets and enable business banking.",
    "url": "https://zenbusiness.com",
    "category": "Business Formation & Administration"
  },
  {
    "name": "FileNow",
    "tagline": "Business Filing & Compliance",
    "description": "Business formation and compliance filing service. LLC formation, EIN registration, annual reports, and business licenses. Useful for operators who've already formed an LLC and need ongoing compliance support — annual filing requirements vary by state and can result in dissolution if missed.",
    "url": "https://filenow.com",
    "category": "Business Formation & Administration"
  },
  {
    "name": "PureVPN",
    "tagline": "VPN · Market Research",
    "description": "Use a VPN to access US/UK/AU TikTok feeds from anywhere in the world — essential for product research and seeing what your target market's For You page looks like. Also useful for accessing geo-restricted ad libraries and competitor store pricing.",
    "url": "https://purevpn.com",
    "category": "Utilities"
  },
  {
    "name": "Slash",
    "tagline": "AI Business Card & Spend Tool",
    "description": "Corporate card and spend management built for ecommerce businesses. Create unlimited virtual cards per campaign, set spend limits per ad account, and track ad spend with real-time categorization. Eliminates the chaos of managing ad budgets across multiple accounts on a single credit card.",
    "url": "https://slashfinancial.com",
    "category": "Utilities"
  }
];
